// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.0--rc2
// source: PandaRequest.proto

package my_protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 熊猫消息结构体
type PandaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 名字
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 身高
	High int32 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	// 体重
	Weight []int32 `protobuf:"varint,3,rep,packed,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PandaRequest) Reset() {
	*x = PandaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PandaRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PandaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PandaRequest) ProtoMessage() {}

func (x *PandaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PandaRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PandaRequest.ProtoReflect.Descriptor instead.
func (*PandaRequest) Descriptor() ([]byte, []int) {
	return file_PandaRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PandaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PandaRequest) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PandaRequest) GetWeight() []int32 {
	if x != nil {
		return x.Weight
	}
	return nil
}

type PandaRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 错误号
	Error int32 `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// 错误详情
	ErrorMsg string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

func (x *PandaRespond) Reset() {
	*x = PandaRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PandaRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PandaRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PandaRespond) ProtoMessage() {}

func (x *PandaRespond) ProtoReflect() protoreflect.Message {
	mi := &file_PandaRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PandaRespond.ProtoReflect.Descriptor instead.
func (*PandaRespond) Descriptor() ([]byte, []int) {
	return file_PandaRequest_proto_rawDescGZIP(), []int{1}
}

func (x *PandaRespond) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *PandaRespond) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_PandaRequest_proto protoreflect.FileDescriptor

var file_PandaRequest_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x61, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0c, 0x50, 0x61, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x41, 0x0a, 0x0c, 0x50, 0x61, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x0d, 0x2e, 0x50, 0x61, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x50, 0x61, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x75, 0x79, 0x69, 0x2d, 0x68, 0x75, 0x62, 0x2f, 0x6d, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PandaRequest_proto_rawDescOnce sync.Once
	file_PandaRequest_proto_rawDescData = file_PandaRequest_proto_rawDesc
)

func file_PandaRequest_proto_rawDescGZIP() []byte {
	file_PandaRequest_proto_rawDescOnce.Do(func() {
		file_PandaRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_PandaRequest_proto_rawDescData)
	})
	return file_PandaRequest_proto_rawDescData
}

var file_PandaRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PandaRequest_proto_goTypes = []interface{}{
	(*PandaRequest)(nil), // 0: PandaRequest
	(*PandaRespond)(nil), // 1: PandaRespond
}
var file_PandaRequest_proto_depIdxs = []int32{
	0, // 0: SearchService.Search:input_type -> PandaRequest
	1, // 1: SearchService.Search:output_type -> PandaRespond
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PandaRequest_proto_init() }
func file_PandaRequest_proto_init() {
	if File_PandaRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PandaRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PandaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PandaRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PandaRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PandaRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PandaRequest_proto_goTypes,
		DependencyIndexes: file_PandaRequest_proto_depIdxs,
		MessageInfos:      file_PandaRequest_proto_msgTypes,
	}.Build()
	File_PandaRequest_proto = out.File
	file_PandaRequest_proto_rawDesc = nil
	file_PandaRequest_proto_goTypes = nil
	file_PandaRequest_proto_depIdxs = nil
}
